#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products
/products:
  get:
    description: to get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID":"73657467",
                "productName": "Chinna Mule Course",
                "productProvider": "udemey",
                "productDescription": "complete mule developer course"
              }
              





